# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.02962285 0.58594706 0.99750962]
  [0.04689985 0.75040838 0.06577806]
  [0.75890545 0.39259293 0.62197441]]

 [[0.06863966 0.89742069 0.74702921]
  [0.21315022 0.2306894  0.52693751]
  [0.7769692  0.47076911 0.43300775]]

 [[0.20177601 0.95719053 0.4295881 ]
  [0.04098136 0.38620964 0.8019626 ]
  [0.4245722  0.42598494 0.43405309]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.74227818 0.62995378 0.41648362]
 [0.89739602 0.05442806 0.77127031]
 [0.62987011 0.32713449 0.01536422]]
After normalization:
[[0.82413577 0.69678844 0.4547675 ]
 [1.         0.04428846 0.85700548]
 [0.69669357 0.35346828 0.        ]]


# 5.  How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-08-01
Today:  2020-08-02
Tomorrow:  2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np
a = np.random.randint(0,2,6)
print("First array:")
print(a)
b = np.random.randint(0,2,6)
print("Second array:")
print(b)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(a, b)
print(array_equal)

First array:
[0 0 1 1 1 0]
Second array:
[0 0 0 1 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.24183222 0.18456377 0.77756416 0.74288331 0.23484918 0.85201397
 0.9431276  0.09109374 0.02363685 0.32044596]
Maximum value replaced by -1:
[0.24183222 0.18456377 0.77756416 0.74288331 0.23484918 0.85201397
 0.         0.09109374 0.02363685 0.32044596]


# 9. How to print all the values of an array?

In [15]:
import numpy as np

x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [16]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.99573615 0.1972568  0.4291254  0.17155283 0.84345425 0.52170993
  0.35608255 0.6458536  0.96568899 0.99649871]
 [0.86026646 0.85874557 0.33690936 0.94853033 0.84914414 0.17048159
  0.82185689 0.65622569 0.94942051 0.96439724]
 [0.15988862 0.00471133 0.69286682 0.13574813 0.11500781 0.46870169
  0.42101955 0.89028659 0.5242289  0.76579744]
 [0.88484037 0.78813722 0.81191766 0.07387115 0.54124159 0.26200478
  0.85278144 0.47529898 0.04028633 0.76835964]
 [0.71239153 0.6881331  0.04554086 0.34267406 0.59811763 0.25524466
  0.2087187  0.91426465 0.48143505 0.70156835]]

Subtract the mean of each row of the said matrix:

[[ 0.38344023 -0.41503912 -0.18317052 -0.44074309  0.23115832 -0.09058599
  -0.25621337  0.03355768  0.35339307  0.38420279]
 [ 0.11866869  0.11714779 -0.40468842  0.20693256  0.10754636 -0.57111619
   0.08025911 -0.08537208  0.20782274  0.22279946]
 [-0.25793707 -0.41311436  0.27504113 -0.28207756 -0.30281788  0.05087601
   0.00319386  0.4724609   0.1

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [3]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 3. 4. 3. 3. 3. 1. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [2]:
import numpy as np
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 32, 158,  31])

# 13.How to find the most frequent value in an array?

In [17]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[8 9 8 6 4 9 6 7 9 5 7 5 9 2 5 9 8 1 0 1 0 4 3 9 5 2 7 9 2 8 8 5 7 8 7 2 3
 1 2 8]
Most frequent value in the above array:
8


# 14.How to get the n largest values of an array

In [18]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [19]:
import numpy as np
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
